version: "3"

services:
  song-service:
    hostname: song-service
    container_name: "song-service"
    image: song-service:2.0.1
    ports:
      - "8022:8022"
    depends_on:
      - song-service-db
    env_file:
      - "song-service/song.service.env"

  song-service-db:
    hostname: song-service-db
    container_name: "song-service-db"
    image: song-service-db:2.0.1
    ports:
      - "5306:3306"

  resource-service:
    container_name: "resource-service"
    hostname: resource-service
    image: resource-service:2.0.1
    ports:
      - "8026:8026"
    depends_on:
      - resource-service-db
      - song-service
    env_file:
      - "resource-service/resource.service.env"

  resource-service-db:
    hostname: resource-service-db
    container_name: "resource-service-db"
    image: resource-service-db:2.0.1
    ports:
      - "4306:3306"


