apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: song-pvc
  namespace: k8s-program
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: song-pv
---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-pvc
  namespace: k8s-program
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: resource-pv

