apiVersion: v1
kind: Service
metadata:
  name: resource-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: resource-service-pod
  ports:
    - protocol: "TCP"
      port: 8026
      targetPort: 8026

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-service
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: resource-service-pod
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: resource-service-pod
        owner: katerinaCharakhovich
    spec:
      containers:
        - name: resource-service-container
          image: charakhovich/resource-service:3.0.0
          ports:
            - containerPort: 8026
          envFrom:
            - configMapRef:
                name: resource-service-config
          env:
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: resource-service-db-secret
                  key: username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resource-service-db-secret
                  key: password
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8026
            initialDelaySeconds: 120
            periodSeconds: 10
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health/liveness
              port: 8026
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health/readiness
              port: 8026
            initialDelaySeconds: 120
            periodSeconds: 3