

apiVersion: v1
kind: Service
metadata:
  name: song-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: song-service-pod
  ports:
    - protocol: "TCP"
      port: 8022
      targetPort: 8022

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: song-service-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: song-service-pod
        owner: katerinaCharakhovich
    spec:
      containers:
        - name: song-service-container
          image: charakhovich/song-service:1.0.1
          ports:
            - containerPort: 8022
