

apiVersion: v1
kind: Service
metadata:
  name: song-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: song-service-pod
  ports:
    - protocol: "TCP"
      port: 8022
      targetPort: 8022

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: song-service-pod
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: song-service-pod
        owner: katerinaCharakhovich
    spec:
      containers:
        - name: song-service-container
          image: charakhovich/song-service:3.0.0
          ports:
            - containerPort: 8022
          envFrom:
          - configMapRef:
             name: song-service-config
          env:
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: song-service-db-secret
                  key: username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: song-service-db-secret
                  key: password
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8022
            initialDelaySeconds: 120
            periodSeconds: 3
          readinessProbe:
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /actuator/health/readiness
              port: 8022
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /actuator/health/liveness
              port: 8022